dsn: sqlite://./__dsn.sqlite3?_fk=true&mode=rwc&_vacuum=incremental&_journal=wal&_sync=normal  #memory

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
      allowed_origins:
        - http://127.0.0.1
        - https://jerryc05.icu
        - https://*.jerryc05.icu
      allowed_methods:
        - POST
      max_age: 300
      debug: true
  admin:
    base_url: http://127.0.0.1:4434/
    host: 127.0.0.1

selfservice:
  default_browser_return_url: http://127.0.0.1:4455/
  allowed_return_urls:
    - http://127.0.0.1:4455

  methods:
    password:
      enabled: true

  flows:
    error:
      ui_url: http://127.0.0.1:4455/error

    settings:
      ui_url: http://127.0.0.1:4455/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:4455/recovery

    verification:
      enabled: true
      ui_url: http://127.0.0.1:4455/verify
      after:
        default_browser_return_url: http://127.0.0.1:4455/

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:4455/auth/login

    login:
      ui_url: http://127.0.0.1:4455/auth/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:4455/auth/registration
      after:
        password:
          hooks:
            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  #cookie:
  #  - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  default:
    - #  TODO: 'echo $(head /dev/urandom | tr -dc A-Za-z0-9 | head -c64)'

hashers:
  algorithm: argon2
  argon2:
    #parallelism: 1
    memory: 4MB  #128MB （default）is much safer but slow
    #iterations: 2
    #salt_length: 16
    #key_length: 16
    expected_duration: 0ms  # 500m is much safer but slow
    expected_deviation: 0ms  # 500m is much safer but slow

identity:
  schemas:
    #- id: user_type_v0  # deprecated, keep for compatibility
    #  url: file://somewhere
    - id: users_v1
      url: file://./schema_users_v1.json
    - id: admins_v1
      url: file://./schema_users_v1.json
  default_schema_id: users_v1

courier:
 smtp:
   connection_uri: smtps://  #test:test@mailslurper:1025/?skip_ssl_verify=true&legacy_ssl=true






cookies:
  domain: "jerryc05.icu"

session:
  cookie:
    name: "sso_sess"
  whoami:
    required_aal: aal1

sqa-opt-out: false
