dsn: sqlite://./__dsn.sqlite3?_fk=true&mode=rwc&_vacuum=incremental&_journal=wal&_sync=normal  #memory

serve:
  public:
    base_url: https://sso.jerryc05.icu/
    host: 127.0.0.1
    port: 4433
    cors:
      enabled: true
      allowed_origins:
        - http://127.0.0.1
        - https://jerryc05.icu
        - https://*.jerryc05.icu
      max_age: 300
  admin:
    base_url: http://127.0.0.1:4434/
    host: 127.0.0.1
    port: 4434

selfservice:
  default_browser_return_url: https://sso.jerryc05.icu/
  allowed_return_urls:
    - https://jerryc05.icu
    - https://*.jerryc05.icu

  methods:
    password:
      config:
        min_password_length: 6
        max_breaches: 100
        identifier_similarity_check_enabled: false
      enabled: true
    totp:
      config:
        issuer: "jerryc05.icu"
      enabled: true
    lookup_secret:
      enabled: true
    webauthn:
      config:
        rp:
          id: jerryc05.icu
          display_name: Jerryc05's Website
          icon: https://jerryc05.icu/favicon.ico
        passwordless: false
      enabled: true

  flows:
    error:
      ui_url: https://sso.jerryc05.icu/error

    settings:
      ui_url: https://sso.jerryc05.icu/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: https://sso.jerryc05.icu/recovery

    verification:
      enabled: true
      ui_url: https://sso.jerryc05.icu/verification
      after:
        default_browser_return_url: https://sso.jerryc05.icu/

    logout:
      after:
        default_browser_return_url: https://sso.jerryc05.icu/login

    login:
      ui_url: https://sso.jerryc05.icu/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: https://sso.jerryc05.icu/registration
      after:
        password:
          hooks:
            - hook: session

log:
  format: text

secrets:
  #cookie:
  #  - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  default:
    - #  TODO: 'echo $(head /dev/urandom | tr -dc A-Za-z0-9 | head -c64)'

hashers:
  algorithm: argon2
  argon2:
    #parallelism: 1
    memory: 4MB  #128MB （default）is much safer but slow
    #iterations: 2
    #salt_length: 16
    #key_length: 16
    expected_duration: 0ms  # 500m is much safer but slow
    expected_deviation: 0ms  # 500m is much safer but slow

identity:
  schemas:
    #- id: user_type_v0  # if deprecated, keep it for compatibility
    #  url: file://somewhere
    - id: users_v1
      url: file://./schema_users_v1.json
    - id: admins_v1
      url: file://./schema_users_v1.json
  default_schema_id: users_v1

courier:
 smtp:
   connection_uri: smtps://  #test:test@mailslurper:1025/?skip_ssl_verify=true&legacy_ssl=true






cookies:
  domain: "jerryc05.icu"

session:
  cookie:
    name: "sso_sess"
  whoami:
    required_aal: aal1

version: v1.0.0
