#!/usr/bin/env sh

##################################################
# [B]uild [R]elease version with [build-std] arg #
##################################################

#  rustup toolchain install nightly
#  rustup component add rust-src --toolchain nightly

CARGO_BUILD_RUSTFLAGS='-Clink-arg=-fuse-ld=lld' \
cargo br \
-Zbuild-std=std,panic_abort \
-Zbuild-std-features=panic_immediate_abort \
--target=`rustc -vV|sed -n "s|host: ||p"`
