#!/usr/bin/env sh

####################################################
# [C]reate a version with [build-std] optimization #
####################################################

#  rustup toolchain install nightly
#  rustup component add rust-src --toolchain nightly

if [ ${#1} -ne 2 ]; then
  cargo $1
else
  cargo $1 \
-Zunstable-options \
--config='profile.release.rustflags=["-Clink-arg=-fuse-ld=lld","-Clinker-plugin-lto"]' \
-Zbuild-std=std,panic_abort \
-Zbuild-std-features=panic_immediate_abort \
--target=`rustc -vV|sed -n "s|host: ||p"`
fi
